### ISSUE TITLE
Parts of UI disappear based on window scale

### ISSUE THREAD

**Issue by afefafafe** [fireclawthefox/FRAME#1] opened 2022-04-12 01:46 UTC
I know that this project is in it's early stage so I hope it's okay for me to file an issue.

As for my issue when I launch FRAME I can't see the panel with the buttons to use the SceneEditor and DirectGuiDesigner.

![image](https://user-images.githubusercontent.com/54505044/162857934-9d9d176c-f251-437f-b0ca-01f1c1043dcc.png)

If I widen the screen though I can see the panel with the buttons but the project button disappears. Also this the buttons don't seem to work (the only one that does anything is the GUI Designer button which causes a grid to appear).

![image](https://user-images.githubusercontent.com/54505044/162857969-abf7448f-72a2-47c7-ad29-df5e48130af4.png)

Finally if I increase the height of the window neither the project button or the side panel appears and instead this weird white box appears where the project button was located.

![image](https://user-images.githubusercontent.com/54505044/162858008-4a33a174-ce35-4256-8cc1-51dd6ce8f642.png)

I'm using the most up to date version of Panda3d, I have both SceneEditor and DirectGuiDesigner installed (all via PyPi), I'm using Python 3.9, and am running Windows 10.

**Comment by fireclawthefox** [comment] 2022-04-12 05:00
Thank you very much for the report. It's actually the best you can do at this stage.

I'll take a look at this problem and see if I can reproduce it on my windows PC later today. As of yet it's only tested on Linux. In addition, can you also tell me what happens if you shrink down the window a bit?

**Comment by fireclawthefox** [comment] 2022-04-12 11:17
Ok, I'm able to reproduce this bug on my windows machine. Seems to be OS specific.
Will try to fix this soon but as of yet I haven't found the root causes of this behavior.

**Comment by fireclawthefox** [comment] 2022-04-14 15:55
Seems to occur due to some miscalculations in the DirectBoxSizer element and maybe also some update problem in the DirectAutoSizer (may get fixed with the box sizer changes though) which is used here. I'll need to rewrite some of this code to give it a better structure and make it more easy to manage.
As those are larger changes to be made right and require throughout testing, this bug will probably take some time to be fixed. But it'll be my main priority for now.

**Comment by fireclawthefox** [comment] 2022-04-30 15:37
Took quite some time but it was a fundamental and important thing to fix.

I've uploaded new builds of the DirectGuiExtensions (22.04), DirectGuiDesigner (22.04.1 and SceneEditor (22.04.1). Update it with pip and you should be good to go.

Thanks again for reporting this problem. Feel free to reopen it if you encounter it again or open a new bug.

**Closed as completed by fireclawthefox** 2022-04-30 15:37 UTC
